load("@rules_java//java:defs.bzl", "java_library")

# Data structures library - organized by subdirectories

java_library(
    name = "all_datastructures",
    exports = [
        "//src/main/java/com/williamfiset/algorithms/datastructures/balancedtree:balancedtree",
        "//src/main/java/com/williamfiset/algorithms/datastructures/binarysearchtree:binarysearchtree",
        "//src/main/java/com/williamfiset/algorithms/datastructures/bloomfilter:bloomfilter",
        "//src/main/java/com/williamfiset/algorithms/datastructures/dynamicarray:dynamicarray",
        "//src/main/java/com/williamfiset/algorithms/datastructures/fenwicktree:fenwicktree",
        "//src/main/java/com/williamfiset/algorithms/datastructures/fibonacciheap:fibonacciheap",
        "//src/main/java/com/williamfiset/algorithms/datastructures/hashtable:hashtable",
        "//src/main/java/com/williamfiset/algorithms/datastructures/kdtree:kdtree",
        "//src/main/java/com/williamfiset/algorithms/datastructures/linkedlist:linkedlist",
        "//src/main/java/com/williamfiset/algorithms/datastructures/priorityqueue:priorityqueue",
        "//src/main/java/com/williamfiset/algorithms/datastructures/quadtree:quadtree",
        "//src/main/java/com/williamfiset/algorithms/datastructures/queue:queue",
        "//src/main/java/com/williamfiset/algorithms/datastructures/segmenttree:segmenttree",
        "//src/main/java/com/williamfiset/algorithms/datastructures/set:set",
        "//src/main/java/com/williamfiset/algorithms/datastructures/skiplist:skiplist",
        "//src/main/java/com/williamfiset/algorithms/datastructures/sparsetable:sparsetable",
        "//src/main/java/com/williamfiset/algorithms/datastructures/stack:stack",
        "//src/main/java/com/williamfiset/algorithms/datastructures/suffixarray:suffixarray",
        "//src/main/java/com/williamfiset/algorithms/datastructures/trie:trie",
        "//src/main/java/com/williamfiset/algorithms/datastructures/unionfind:unionfind",
        "//src/main/java/com/williamfiset/algorithms/datastructures/utils:utils",
    ],
)
