language: java
install: skip

dist: trusty

jdk:
  - oraclejdk8

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - ./cc-test-reporter before-build

script:
  - ./gradlew googleJavaFormat
  - ./gradlew build
  - ./gradlew test sonarqube -Dsonar.host.url=https://sonar.josdem.io

 