language: java
install: skip

dist: trusty

jdk:
  - oraclejdk8

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
     organization: "yulingggg"
     token:
       secure: $SONAR_TOKEN
  apt:
    packages:
      - oracle-java8-installer
  

script:
  - ./gradlew googleJavaFormat
  - ./gradlew build
  - ./gradlew test 
  - ./gradlew jacocoTestReport
  - sonar-scanner

jobs:
   include:
     - stage: "Unit Tests & SonarCloud Analysis"
       script:
         - gradle jacocoTestReport
         - gradle sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY

