language: java
install: skip

dist: trusty

jdk:
  - oraclejdk8

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./gradlew googleJavaFormat
  - ./gradlew build
  - ./gradlew test sonarqube -Dsonar.host.url=https://sonar.josdem.io

 cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'