#!/bin/bash

for DIR in */
do

  cd $DIR
  echo "In directory: " $DIR

  if [ -d "tests" ]; then 

    foundFiles="$(find ./tests -name '*Test.java')"
    test_files=($foundFiles)
    numTestFiles=${#test_files[@]}

    # Found some java test files :)
    if [ $numTestFiles -ne 0 ]; then
      
      # Oops not able to compile java scripts
      if ! javac -cp .:../junit-4.12.jar *.java tests/*Test.java -d .; then
        echo "Error compiling java files"
        exit 1
      fi
      
      for (( i=0; i<${numTestFiles}; i++ ));
      do
    
        class_test_file=${test_files[$i]}
        echo "Executing: " $class_test_file
    
        # Trim .java to remove leading "./" and ending ".java" characters
        test_file=${class_test_file::${#class_test_file}-5}
        test_file=${test_file:8}
    
        if ! java -cp .:../junit-4.12.jar:../hamcrest-core-1.3.jar org.junit.runner.JUnitCore $test_file; then
          exit 1
        fi
    
      done
      
      rm *.class 2> /dev/null
    
    fi

  fi
  
  cd ..

done
