#!/bin/sh
# Format all java files according to the Google Java Code Style guide.
# This hook triggers (on the client side?) when a commit happens.
# 
# Article
# https://medium.com/@harshitbangar/automatic-code-formatting-with-git-66c3c5c26798

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$") || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    "${REPO_ROOT_DIR}/gradlew" goJF -DgoogleJavaFormat.include="$comma_files" &>/dev/null
    git add $(echo "$files" | paste -s -d " " -)
fi
