load("@rules_java//java:defs.bzl", "java_library")

# Bloom filter implementations library
java_library(
    name = "bloomfilter",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
