load("@rules_java//java:defs.bzl", "java_library")

# Hash table implementations library
java_library(
    name = "hashtable",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
