load("@rules_java//java:defs.bzl", "java_library")

# Fibonacci heap implementation library
java_library(
    name = "fibonacciheap",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
