load("@rules_java//java:defs.bzl", "java_library")

# Union-Find (Disjoint Set) implementation library
java_library(
    name = "unionfind",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
