load("@rules_java//java:defs.bzl", "java_library")

# Priority queue implementations library
java_library(
    name = "priorityqueue",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
