load("@rules_java//java:defs.bzl", "java_library")

# Fenwick tree (Binary Indexed Tree) implementations library
java_library(
    name = "fenwicktree",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
