load("@rules_java//java:defs.bzl", "java_library")

# Linked list implementations library
java_library(
    name = "linkedlist",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
