# This workflow checks that the code in the repo is formatted according to the
# Google Java Style Guide

name: Code Formatting Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Verify all Java files are formatted correctly according to the Google Java Style Guide
      run: |
        ./gradlew verifyGoogleJavaFormat
        echo "Run the command './gradlew goJF' to fix Java formatting if this workflow fails"
