
name: Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2
    - uses: dbelyaev/action-checkstyle@v0.5.1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning
